version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"  # Expose Streamlit app on port 8501
    volumes:
      - .:/app  # Bind mount the entire project root to /app
      - logs:/app/logs  # Named volume for logs
    working_dir: /app  # Ensure the container starts in the correct directory
    environment:
      - STREAMLIT_CONFIG=/app/config.toml  # Example environment variable
    restart: always  # Restart the service if it crashes

volumes:
  logs:  # Persistent volume for logs
