version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"  # Map container port 8501 to host
    volumes:
      - ./app:/app  # Bind mount for app code (hot-reload enabled)
      - logs:/app/logs  # Named volume for logs
    environment:
      - STREAMLIT_CONFIG=/app/config.toml  # Example of passing environment variables
    restart: always  # Restart if stopped

volumes:
  logs:  # Persistent volume for logs
